### ISSUE TITLE
Php version?

### ISSUE THREAD

**Issue by MrMoronIV** [tmthrgd/mpw-js#13]
I would like to implement a php version of this so it can be used using an API in my own app. Is there an implementation of this algorithm in php somewhere?

Also the open issue of the Edge browser giving different results wories me a bit for this js implementation, maybe giving different results per platform, hence the php aproach :)

**Comment by tmthrgd** [comment]
As far as I’m aware no there isn’t. There is a reference C version and a Java version in the official https://gitlab.com/MasterPassword/MasterPassword repository.

Perhaps you could use the C version from PHP (it’s been years since I wrote PHP). Otherwise the algorithm is described [here](https://masterpassword.app/masterpassword-algorithm.pdf) with test vectors available [here](https://github.com/Lyndir/MasterPassword/blob/master/core/mpw_tests.xml). If you do go down that route, make sure you use solid, well-implemented cryptographic implantations. 

Regarding #8, I unfortunately don’t have easy access to a Windows machine with Edge installed to debug what’s going on. Any help on that would be appreciated, even just running the test suite at https://tmthrgd.github.io/mpw-js/test/.

I’m going to close this issue as I don’t think there’s anything actionable here.
